# Generated by Django 2.1.4 on 2020-07-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200701_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
    ]
